version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # ignore patch updates for all dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
